### ISSUE TITLE
Duplicate Id after 1.0.9 upgrade

### ISSUE THREAD

**Issue by AmedeeBulle** [bertouttier/flukso-hacs#11]
After upgrading to 1.0.9 (or 1.0.10), Home Assistant (2022.11.5) complains about duplicate id for all Flukso sensors:

```
hass_1      | 2022-12-03 19:18:18.753 ERROR (MainThread) [homeassistant.components.sensor] Platform flukso does not generate unique IDs. ID 688d2bdab6d733ee02ff88b4eadd95f5_538e5b386f0415a1fa704ba7d4de1edc_gauge is already used by sensor.electricity_electricity_gauge - ignoring sensor.electricity_electricity_gauge
hass_1      | 2022-12-03 19:18:18.761 ERROR (MainThread) [homeassistant.components.sensor] Platform flukso does not generate unique IDs. ID 688d2bdab6d733ee02ff88b4eadd95f5_538e5b386f0415a1fa704ba7d4de1edc_counter is already used by sensor.electricity_electricity_counter - ignoring sensor.electricity_electricity_counter
hass_1      | 2022-12-03 19:18:18.764 ERROR (MainThread) [homeassistant.components.sensor] Platform flukso does not generate unique IDs. ID 688d2bdab6d733ee02ff88b4eadd95f5_c60205b98f6f20ff427fc5cba2ecb916_gauge is already used by sensor.water_water_gauge - ignoring sensor.water_water_gauge
hass_1      | 2022-12-03 19:18:18.767 ERROR (MainThread) [homeassistant.components.sensor] Platform flukso does not generate unique IDs. ID 688d2bdab6d733ee02ff88b4eadd95f5_c60205b98f6f20ff427fc5cba2ecb916_counter is already used by sensor.water_water_counter - ignoring sensor.water_water_counter                  
hass_1      | 2022-12-03 19:18:18.771 ERROR (MainThread) [homeassistant.components.sensor] Platform flukso does not generate unique IDs. ID 688d2bdab6d733ee02ff88b4eadd95f5_3b9b4607e090eaa86eb654f1cc37c123_gauge is already used by sensor.gas_gas_gauge - ignoring sensor.gas_gas_gauge                                      
hass_1      | 2022-12-03 19:18:18.774 ERROR (MainThread) [homeassistant.components.sensor] Platform flukso does not generate unique IDs. ID 688d2bdab6d733ee02ff88b4eadd95f5_3b9b4607e090eaa86eb654f1cc37c123_counter is already used by sensor.gas_gas_counter - ignoring sensor.gas_gas_counter  
```
(messages repeated numerous times)

Messages disappear when downgrading to 1.0.8.

**Comment by bertouttier** [comment]
Can you check your config entries database? Do you have the same Flukso device configured twice by any chance?

**Comment by AmedeeBulle** [comment]
Just one...

```
$ jq '.data.entries[] | select(.domain == "flukso")' core.config_entries
{
  "entry_id": "0aea7717e51c87a7bd65dad703d2cd49",
  "version": 1,
  "domain": "flukso",
  "title": "Flukso 688d2bdab6d733ee02ff88b4eadd95f5",
  "data": {
    "device_hash": "688d2bdab6d733ee02ff88b4eadd95f5"
  },
  "options": {},
  "pref_disable_new_entities": false,
  "pref_disable_polling": false,
  "source": "user",
  "unique_id": "flukso_688d2bdab6d733ee02ff88b4eadd95f5",
  "disabled_by": null
}
```

(same output with 10.8 or 1.0.10 installed)

**Comment by bertouttier** [comment]
Can you try deleting the config entry and adding it again?

**Comment by AmedeeBulle** [comment]
I am a bit reluctant to do that, as I don't want to loose the history in the energy dashboard...

I'll see if I can export the setup and test on another machine

**Comment by AmedeeBulle** [comment]
I made some tests on another box (copy of the _production_), and deleting the integration doesn't help...

**Comment by AmedeeBulle** [comment]
FYI, more verbose logs when registering:

```
hass-hass-1  | 2022-12-28 21:36:44.663 INFO (MainThread) [custom_components.flukso.config_flow] Creating new entry for Flukso 688d2bdab6d733ee02ff88b4eadd95f5                           
hass-hass-1  | 2022-12-28 21:36:44.684 DEBUG (MainThread) [custom_components.flukso.discovery] storing config type sensor for device 688d2bdab6d733ee02ff88b4eadd95f5                    
hass-hass-1  | 2022-12-28 21:36:48.698 DEBUG (MainThread) [custom_components.flukso.discovery] test tap pending, FLM02?                                                                  
hass-hass-1  | 2022-12-28 21:36:48.699 DEBUG (MainThread) [custom_components.flukso.discovery] all configs and tap received                                                              
hass-hass-1  | 2022-12-28 21:36:48.700 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.flukso                                                                      
hass-hass-1  | 2022-12-28 21:36:48.701 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.flukso                                                        
hass-hass-1  | 2022-12-28 21:36:48.761 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.flukso entity: sensor.electricity_electricity_gauge               
hass-hass-1  | 2022-12-28 21:36:48.761 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.flukso entity: sensor.electricity_electricity_counter             
hass-hass-1  | 2022-12-28 21:36:48.762 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.flukso entity: sensor.water_water_gauge                           
hass-hass-1  | 2022-12-28 21:36:48.762 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.flukso entity: sensor.water_water_counter          
hass-hass-1  | 2022-12-28 21:36:48.762 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.flukso entity: sensor.gas_gas_gauge                
hass-hass-1  | 2022-12-28 21:36:48.762 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.flukso entity: sensor.gas_gas_counter              
hass-hass-1  | 2022-12-28 21:36:48.762 ERROR (MainThread) [homeassistant.components.sensor] Platform flukso does not generate unique IDs. ID 688d2bdab6d733ee02ff88b4eadd95f5_538e5b386f0
415a1fa704ba7d4de1edc_gauge is already used by sensor.electricity_electricity_gauge - ignoring sensor.electricity_electricity_gauge                                       
hass-hass-1  | 2022-12-28 21:36:48.763 ERROR (MainThread) [homeassistant.components.sensor] Platform flukso does not generate unique IDs. ID 688d2bdab6d733ee02ff88b4eadd95f5_538e5b386f0
415a1fa704ba7d4de1edc_counter is already used by sensor.electricity_electricity_counter - ignoring sensor.electricity_electricity_counter 
...
```

**Comment by AmedeeBulle** [comment]
It is most probably related to the FLM02A...

I created a new setup from scratch. With 1.0.10, there is no error message but it shows no entities:
<img width="306" alt="Screenshot 2022-12-29 at 10 44 15" src="https://user-images.githubusercontent.com/4170863/209933717-af332896-a674-4e61-a186-e89669901c68.png">

Downgrade to 1.0.8 works as expected:
<img width="306" alt="Screenshot 2022-12-29 at 10 40 28" src="https://user-images.githubusercontent.com/4170863/209933806-684fe99c-29e4-4609-a810-55070403145b.png">

Upgrade to 1.0.10: entities are still defined, but marked as unavailable...

**Comment by AmedeeBulle** [comment]
While there is little (no) documentation on the subject, I believe the way entities are registered is not as it should be...

I spent quite some time in the debugger and it doesn't seem right.

The partial
https://github.com/bertouttier/flukso-hacs/blob/1defacc4fd1c2a4964b97b64b55d62cf3fbcc548/custom_components/flukso/sensor.py#L15-L17

is called from the [`async_setup_entry_helper`](https://github.com/home-assistant/core/blob/9cf86b234bb5b9c86e7abb9b9ae450770429beb3/homeassistant/components/mqtt/mixins.py#L308) mixin in 2 places: in `async_discover` and in `_async_setup_entities`.
In our case, it is only called from `_async_setup_entities` which I believe is wrong as this should only happen for entities defined in the yaml config.

As a side effect if you don't have any mqtt definition in yaml, `config_yaml` in the below block eveluates to false, and no entities are added for Flukso...

https://github.com/home-assistant/core/blob/9cf86b234bb5b9c86e7abb9b9ae450770429beb3/homeassistant/components/mqtt/mixins.py#L350-L356

(Which is why I have no entities on a fresh install, it seems to work when I add a _dummy_ mqtt entity)

**Comment by mozreactor** [comment]
> (Which is why I have no entities on a fresh install, it seems to work when I add a _dummy_ mqtt entity)

Well done on the hard work tracking this down!  I simply added:
```
mqtt:
  sensor:
    - name: "dummy"
      state_topic: "dummy"
```     
to my `configuration.yaml` and - bang - my FLM02A (fw250) has its entities populated.

**Comment by AmedeeBulle** [comment]
I also have reproduced the issue I initially reported...

If you have multiple MQTT sensors defined in the config YAML file (and I do have quite a lot), `_async_setup_entity` will be invoked for each sensor definition, attempting to create duplicate entries for flukso an produce the above error...

Calling `async_add_entities` directly from `async_setup_entry` (like we had in 1.0.8) seems to solve the problem (testing against the `dev` branch of hass)-- it doesn't trigger the `Manually configured MQTT...` we had in 1.0.8.
