### ISSUE TITLE
New HA Constants

### ISSUE THREAD

**Issue by freekbe** [bertouttier/flukso-hacs#13]
Multiple warnings in home-assistant.log since HA Core 2024.1

> ELECTRIC_CURRENT_AMPERE was used from flukso, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricCurrent.AMPERE instead

Similar messages for 
- ELECTRIC_POTENTIAL_VOLT Use UnitOfElectricPotential.VOLT instead
- ENERGY_WATT_HOUR Use UnitOfEnergy.WATT_HOUR instead
- POWER_WATT Use UnitOfPower.WATT instead
- PRESSURE_HPA Use UnitOfPressure.HPA instead
- TEMP_CELSIUS Use UnitOfTemperature.CELSIUS instead
- VOLUME_CUBIC_METERS Use UnitOfVolume.CUBIC_METERS instead
- VOLUME_LITERS UnitOfVolume.LITERS instead

**Comment by bertouttier** [comment]
thanks! Created a PR. Let me know if you have comments, otherwise I'll merge it.
