### ISSUE TITLE
Stopped working on 2022.03

### ISSUE THREAD

**Issue by vk2him** [bertouttier/flukso-hacs#3]
Hi, I updated to 2022.03 today and this stopped working with the following error in the logs:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/flukso/discovery.py:479
Integration: Flukso (documentation, issues)
First occurred: 12:00:31 PM (1 occurrences)
Last logged: 12:00:31 PM

Error setting up entry Flukso fe779fdxxxxxxxxxxxxx for flukso
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/flukso/__init__.py", line 26, in async_setup_entry
    await async_discover_device(hass, entry)
  File "/config/custom_components/flukso/discovery.py", line 479, in async_discover_device
    sub_state = await subscription.async_subscribe_topics(
TypeError: async_subscribe_topics() takes 2 positional arguments but 3 were given

**Comment by bollewolle** [comment]
Same issue here. I believe it's because of a breaking mqtt change they did in a previous release, but could be wrong.

Did a quick fix like explained below in the discovery.py file that seemed to work at the moment. But be ware, I'm not a particularly good programmer, just done this based on deduction of commits made in other repositories.

As of line 479 replace:
```
    sub_state = await subscription.async_subscribe_topics(
        hass,
        sub_state,
        {
            f"tap_topic_{hass.data[DOMAIN][entry.entry_id][CONF_DEVICE_HASH]}": {
                "topic": f"/device/{hass.data[DOMAIN][entry.entry_id][CONF_DEVICE_HASH]}/test/tap",
                "msg_callback": tap_message_received,
            },
            f"config_topic_{hass.data[DOMAIN][entry.entry_id][CONF_DEVICE_HASH]}": {
                "topic": f"/device/{hass.data[DOMAIN][entry.entry_id][CONF_DEVICE_HASH]}/config/+",
                "msg_callback": config_message_received,
            },
        },
    )
```

With:
```
    sub_state = subscription.async_prepare_subscribe_topics(
        hass,
        sub_state,
        {
            f"tap_topic_{hass.data[DOMAIN][entry.entry_id][CONF_DEVICE_HASH]}": {
                "topic": f"/device/{hass.data[DOMAIN][entry.entry_id][CONF_DEVICE_HASH]}/test/tap",
                "msg_callback": tap_message_received,
            },
            f"config_topic_{hass.data[DOMAIN][entry.entry_id][CONF_DEVICE_HASH]}": {
                "topic": f"/device/{hass.data[DOMAIN][entry.entry_id][CONF_DEVICE_HASH]}/config/+",
                "msg_callback": config_message_received,
            },
        },
    )

    sub_state = await subscription.async_subscribe_topics(
        hass,
        sub_state,
    )
```

And the last line 503 replace:
```
await subscription.async_unsubscribe_topics(hass, sub_state)
```

With:
```
subscription.async_unsubscribe_topics(hass, sub_state)
```

As mentioned, this might not be the proper solution, but for now it seems to be working for me.

**Comment by bertouttier** [comment]
Fixed in version 1.0.5. Thanks for reporting!

**Comment by walshtj** [comment]
I still seem to have this problem.
I'm on the latest version 1.0.5 and Home Assistant 2022.3.2.
Error as follows:

------------------------------------------
Logger: homeassistant.config_entries
Source: custom_components/flukso/discovery.py:479
Integration: Flukso ([documentation](https://github.com/bertouttier/flukso-hacs), [issues](https://github.com/bertouttier/flukso-hacs/issues))
First occurred: 16:47:50 (1 occurrences)
Last logged: 16:47:50

Error setting up entry Flukso Meter for flukso
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/flukso/__init__.py", line 26, in async_setup_entry
    await async_discover_device(hass, entry)
  File "/config/custom_components/flukso/discovery.py", line 479, in async_discover_device
    sub_state = subscription.async_subscribe_topics(
TypeError: async_subscribe_topics() takes 2 positional arguments but 3 were given
```

**Comment by bertouttier** [comment]
@walshtj can you try to re-download the 1.0.5 and try again?

**Comment by walshtj** [comment]
@bertouttier That worked.  
Thank you and thank you for the integration. It gave my old Flukso meter a new lease of life!
