### ISSUE TITLE
Error when adding flukso component for FLM02B

### ISSUE THREAD

**Issue by SamDeZwam** [bertouttier/flukso-hacs#4]
Hi,

Home Assistant 2022.4.3
Flukso 1.0.6
Device: FLM02B, firmware 250

Following the instructions, I added a MQTT bridge which is working. In the mosquitto broker I can listen to topic /device/6bbbee8xxxxxxxxxxxxxxxcdfc0c1/config/sensor and get feedback.
However when I register the device hash (not the sensor hash) in the Flukso integration, I get the error "Failed to set up"

_This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/flukso/discovery.py:490
Integration: Flukso (documentation, issues)
First occurred: 20:26:51 (1 occurrences)
[flukso.log](https://github.com/flukso/hass_flukso_component/files/8710684/flukso.log)

Last logged: 20:26:51

Error setting up entry Flukso 6bbbee8xxxxxxxxxxxxxxxcdfc0c1 for flukso
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/flukso/init.py", line 26, in async_setup_entry
await async_discover_device(hass, entry)
File "/config/custom_components/flukso/discovery.py", line 490, in async_discover_device
if len(pending) == 1 and config_futures["kube"] == pending[0]:
TypeError: 'set' object is not subscriptable_

[flukso.log](https://github.com/bertouttier/flukso-hacs/files/8718580/flukso.log)

Line 490 in /config/custom_components/flukso/discovery.py is this one:
if len(pending) == 1 and config_futures["kube"] == pending[0]:
_LOGGER.debug("kube config pending, FLM02?")

I have no Kube setup.
In the attached log, the sensors are present, so the connection is made I think.

Any help is appreciated.

Regards,
Sam

**Comment by bertouttier** [comment]
Hi @SamDeZwam 
Thanks for reaching out. Could you test the fix in the linked PR #7 ? 

Thanks!
