### ISSUE TITLE
Wrong units for Gas / FLM02A

### ISSUE THREAD

**Issue by AmedeeBulle** [bertouttier/flukso-hacs#5]
It seems we have the wrong units for the Gas sensor on the FLM02A.

The MQTT stream shows data in Liters / Liters/Day:

```
/sensor/3b9b4607e090eaa86eb654f1cc37c123/counter [1654440504,45287000,"L"]
/sensor/3b9b4607e090eaa86eb654f1cc37c123/gauge [1654440504,130252,"L/day"]
/sensor/3b9b4607e090eaa86eb654f1cc37c123/counter [1654447813,45287100,"L"]
/sensor/3b9b4607e090eaa86eb654f1cc37c123/gauge [1654447813,1184,"L/day"]
```

These are 2 consecutive messages, we have 100L difference, which matches my setup (my gas meter gives 1 pulse per 0,1 cubic meter)

But in Home Assistant I am getting cubic meters instead of liters!

![image](https://user-images.githubusercontent.com/4170863/172062098-f3712d42-e69d-4323-a9e1-5a717d13eb8c.png)

I guess this is coming from

https://github.com/bertouttier/flukso-hacs/blob/786bada40b9aa871aa84c195b9adb9f1cad5f020/custom_components/flukso/discovery.py#L151

(As such I am fine with cubic meters for the sensor, but we should scale the data ;) )

**Comment by bertouttier** [comment]
Indeed, you are right, I missed that scaling. I added a PR that you could test. Let me know if it fixes it!

**Comment by AmedeeBulle** [comment]
With the suggested change I made in the PR, it looks much better now:

![image](https://user-images.githubusercontent.com/4170863/172374154-2c3cb378-3904-4fa3-8074-1c4f93ceba83.png)
